server:
  port: 80

spring:
  application:
    name: game-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: game-auth
          uri: lb://game-auth
          predicates:
            - Path=/game-auth/**
          filters:
            - StripPrefix=1
        - id: game-server
          uri: lb://game-server
          predicates:
            - Path=/game-server/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: localhost:8848

secure:
  ignore:
    urls: # 配置白名单路径
      - /game-auth/user/account/token
      - /game-server/pk/start/game
      - /game-auth/user/account/queryById
      - /game-auth/user/bot/queryBot
      - /game-auth/test


logging:
  pattern:
    console: '%d{HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'